### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by jacksonporter** [SanderKnape/github-runner#1]
There is no license to use this code - I would love to use this in other projects, can one be defined?

**Comment by jacksonporter** [comment]
https://expressionengine.com/blog/the-truth-about-the-risks-of-unlicensed-software

**Comment by jacksonporter** [comment]
That blog links back to GitHub for a great explanation - https://choosealicense.com/no-permission/

Does it seem that this would fit an MIT license if you're willing?

**Comment by SanderKnape** [comment]
Thanks for the heads up - I added a license.

**Comment by jacksonporter** [comment]
Thank you!
