### ISSUE TITLE
No API for creating a registration token for a repository?

### ISSUE THREAD

**Issue by michaelsync** [SanderKnape/github-runner#14]
Thanks for writing this article https://sanderknape.com/2020/03/self-hosted-github-actions-runner-kubernetes/

In that article, it creates the registration token for a repository using this API https://developer.github.com/v3/actions/self-hosted-runners/#create-a-registration-token-for-a-repository. 

But this API is outdated and the new API documentation doesn't seem to have any API for creating the registration token for the repo anymore. It has one for the organization https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#create-a-registration-token-for-an-organization. 

I am getting this error when I run the docker with my personal token. Is it still possible to add the self-hosted runner to the repo? I also read somewhere that we can't use PAT for adding the self-hosted runner. So what do we need to pass? 

```Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Response status code does not indicate success: 404 (Not Found).
An error occurred: Not configured

Thanks.

**Comment by bigfacewo** [comment]
@michaelsync How did you solve the problem？
