### ISSUE TITLE
Allow usage of Repository token to bind the runner, preventing loss of functionality when a user leaves a repository

### ISSUE THREAD

**Issue by 5nafu** [SanderKnape/github-runner#19]
When using the repository-connected runner in a organization or team setup, using a PAT for getting the authorization token might result in the team/organization loosing access to the runner.

Unfortunately this might not happen immediately after the person loses access to the repository, but will happen when the runner pod is restarted.

To remediate it would be great if there would be a possibility to set the `RUNNER_TOKEN` via environment (See line [entrypoint.sh#L13](https://github.com/SanderKnape/github-runner/blob/e3d757ec9969ef35e4468ce5c6ecbf8cf378789f/entrypoint.sh#L13) ) and skip [lines 2-12 in the same file](https://github.com/SanderKnape/github-runner/blob/e3d757ec9969ef35e4468ce5c6ecbf8cf378789f/entrypoint.sh#L2-L12)

This would make the runner independent from the user setting it up.

I would be very happy to supply a pull request for this issue.

**Comment by SanderKnape** [comment]
Fixed by #23
