### ISSUE TITLE
github-runner starts up with CrashLoopBackoff and Error

### ISSUE THREAD

**Issue by darnone** [SanderKnape/github-runner#22]
I have followed the instructions at: https://vitobotta.com/2020/09/29/self-hosted-github-actions-runners-in-kubernetes/  and the pod starts up with CrashLoopBackoff. That is typically an error with the entry point.  I was able to get a log (see below):

I am using vitobotta/github-actions-runner:0.0.5

From the error below it looks like the config.sh argument labels is incorrect??

```
k logs github-runner-6b8db49996-mrtfb -n github-actions
Requesting token at 'https://api.github.com/repos/darnone/Foobar/k8s_helm_charts_lamp_feature_DEVOP-667-ansible/actions/runners/registration-token'
Unrecognized command-line input arguments: 'labels'. For usage refer to: .\config.cmd --help or ./config.sh --help

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Response status code does not indicate success: 404 (Not Found).
An error occurred: Not configured
```

**Comment by darnone** [comment]
I am wondering if the parameters are wrong.  If the repo name is https://githib.com:demo-devops/demo-repo does that make the variables GITHUB_OWNER=demo-devops and the GITHUB_REPOSITORY=demo-repo?  Because currently the  GITHUB _OWNER is my GitHub username and the GITHUB_REPOSITORY is demo-devops/demo-repo.  any assistance is appreciated.

**Comment by SanderKnape** [comment]
Hi @darnone . This isn't the repository for `vitobotta/github-actions-runner` so I'm not sure you're asking this question in the right place?

**Comment by darnone** [comment]
Sorry, I resolved this issue,. Vito. Botta referenced your runner as a starting point for a Docker-in-docker setup here. https://vitobotta.com/2020/09/29/self-hosted-github-actions-runners-in-kubernetes/  I got the repositories switched.  Sorry for the noise

**Comment by SanderKnape** [comment]
No problem! Good to hear you solved it.
